one = float(5)
two = float(5.9)
three = float("5")
four = str(float(5.9))
five = int(float(5.9))
six = str(int(float(5.9)))
# seven = int(str(float(5.9)))
eight = float(str(int(5.9)))
age = 42
# print("You are " + age + " years old")
# print("You are" + age + "years old")
print("You are " + str(age) + " years old")
# print(f"You are {age} years old")
# fourteen = int('2.5')
fifteen = int(float('2.5'))

print(one)
print(two)
print(three)
print(four)
print(five)
print(six)

print(eight)
print(fourteen)
print(fifteen)